name: Build and Deploy to GitHub Packages

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # --- Настройка Maven для GitHub Packages ---
      - name: Create temporary settings.xml with GitHub token
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.M2_GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Build and deploy to GitHub Packages
        run: mvn clean deploy -B -s ~/.m2/settings.xml -DskipTests
